### ISSUE TITLE
iterm2 support

### ISSUE THREAD

**Issue by mooreniemi** [julienXX/terminal-notifier#147] opened 2015-10-29 19:55 UTC
see also: https://github.com/julienXX/terminal-notifier/issues/80

```
terminal-notifier -title "RSPEC" -message "⚑ Tests done."
```

Works in the terminal directly, but if I use "Run command..." in iTerm2 triggers, it doesn't work. I confirmed the trigger was firing correctly (used text highlight to check).

I'm on Yosemite 10.10.5.

**Comment by julienXX** [comment] 2015-11-05 17:20
I'm not an iTerm user so I won't be able to help here. Sorry.

**Comment by mooreniemi** [comment] 2015-11-05 18:04
@julienXX any other collaborators available? if not, feel free to just close this and i'll assume it'll remain unsupported. (i could try to take a look myself but this is a bit outside my wheelhouse :))

**Comment by julienXX** [comment] 2015-11-05 18:07
I'll leave it opened in case someone has an answer.

**Comment by semikolon** [comment] 2015-11-29 00:13
Did you try referencing the binary with the exact path? /usr/local/bin/terminal-notifier or such?

**Comment by shigemk2** [comment] 2015-12-15 01:47
Me neither. My environments are 

* Mac OSX Yosemite
* iTerm2 2.1.4
* terminal-notifier's path is /usr/local/bin/terminal-notifier 

When executing sample command in README, command freezes and I didn't have any results.

```sh
$ echo 'Piped Message Data!' | terminal-notifier -message 'Check your Apple stock!'
// Freezing...
```

**Comment by msaspence** [comment] 2016-01-04 12:58
I tried referencing the exact path and sent the exit code to a txt file and get 127

**Comment by dnakagome** [comment] 2016-01-28 08:56
+1 for @semikolon 

Giving the exact path in "Parameters" for "Run Command..." triggers terminal-notifier perfectly.

I'm using El Capitan though.

My environments are:
- OS X El Capitan 10.11.2
- iTerm2 2.1.4
- terminal-notifier 1.6.3

**Comment by GuidoSchmidt** [comment] 2016-02-06 02:27
Try using the ruby gem - works for me using iTerm2 on OS X 10.11.3

**Comment by ssbarnea** [comment] 2016-02-28 10:29
You can close the bug, I tested and `echo "msg" | terminal-notifier works perfectly.`

Also, for your information iTerm3 has a trigger named Post Notification, which does this without even needing this wrapper.

**Comment by ciudilo** [comment] 2016-03-30 16:22
@ssbarnea does not work in iTerm2 on OS X 10.11.4

**Comment by theoretick** [comment] 2016-05-23 23:31
I too am having issues with this. I wanted more granularity then `Post Notification` provides so I've tested with `terminal-notifier` and `osx-notifier` without success. Not sure what the issue is, but I have successfully used apple script:
`osascript -e 'display notification "Tests Passed" with title "Terminal"'`.

As you can see from my example what I'd really like is to trigger a different icon (reporting app? i'm unfamiliar with how notifications work) so I can easily see a success/failure.  With `osx-notifier` I would do something like:
`osx-notifer --type=pass --message="Specs Passed"`
or
`osx-notifer --type=fail --message="Specs Failed: \1 failures` (with trigger capture groups).

**Comment by williscool** [comment] 2017-05-01 20:14
@ciudilo @theoretick 

thanks to @semikolon 

I figured it out.

You have to use the full path to the executable in the "Run Command" trigger

i.e.

`/usr/local/bin/terminal-notifier -title 'Notification Title' -subtitle 'Server Ready' `

**Comment by julienXX** [comment] 2017-05-13 23:01
Closing the issue, feel free to re-open if needed.

**Closed by julienXX** 2017-05-13 23:01 UTC
Labels: wrapper
