### ISSUE TITLE
terminal-notification exec is blocking

### ISSUE THREAD

**Issue by uudashr** [julienXX/terminal-notifier#223] opened 2017-05-26 03:07 UTC
# Please check everything that applies to your issue:
- [x] I looked in closed issues and it has not already been answered
- [x] My issue appeared with a terminal-notifier update
- [ ] I'm using a tool that uses terminal-notifier (guard-notifier, node-notifier...)

**Mac Version:** macSierra 10.12.5
**terminal-notifier version:** 1.7.0
**Installation method:** homebrew
**Step-by-step reproduction:**
```shell
$ terminal-notifier -message "Lorem ipsum dolor sit amet" -title "Lorem" -activate "com.googlecode.iterm2"
```
It blocks instead exiting the command

**Comment by dkristian** [comment] 2017-05-26 05:59
I can reproduce this too on macOS 10.11.6 (15G1510) after updating to 1.8.0 (via MacPorts) when I pass the optional `-open` argument. The program only exits straight away if I click the notification before it disappears. 

I suspect the fact that it's not exiting cleanly is the reason why I started receiving mail from cron as mentioned in https://github.com/julienXX/terminal-notifier/issues/218#issuecomment-303924021.

**Comment by uudashr** [comment] 2017-05-26 08:04
Same with me... click the notif then continue.
Maybe it blocks because wait for click input, that is why it not exiting

**Comment by chew-z** [comment] 2017-05-27 04:34
+1

**Comment by chew-z** [comment] 2017-05-27 04:37
And when I click on notification I get

```
2017-05-27 11:34:48.920 terminal-notifier[52134:803653] @CONTENTCLICKED
```

**Comment by majorsl** [comment] 2017-05-27 12:06
Noted this too with 1.8.  Even though it isn't supposed to be necessary, I added a -timeout 10 as a temporary work around until the bug is squashed.

**Comment by rr0ss0rr** [comment] 2017-05-27 15:47
I thought the issue was terminal-notifier 1.8 changed the notification type in error to Alerts. I changed it back to Banners in Notification Center.

**Comment by rikai** [comment] 2017-05-30 04:17
I can confirm this with -activate as well. Updated to 1.8 in brew and it stalled out the scripts i was using terminal-notifier as a part of completely, as it blocks further execution. 🚨

**Comment by shalecraig** [comment] 2017-06-01 07:41
Some more digging leads me to _strongly_ suspect that one of `defaults[@"execute"] || defaults[@"open"] || options[@"bundleID"]` evaluates to true, causing `options[@"waitForResponse"] = @YES` to be true. (source [here](https://github.com/julienXX/terminal-notifier/blob/cf25c7bb3d8b564cb7aae16c4bc5426f027fac99/Terminal%20Notifier/AppDelegate.m#L218))

`bundleId` is sourced from `activate`, which is the param in question.

Git blame points me to the @julienXX's recent change to make macos 10.8 / 10.9 no longer supported: https://github.com/julienXX/terminal-notifier/commit/1d40bcf782e0037115233f32bbf38ad121438661#diff-4f90fe8a7b85b78017139b266d8ad8fbR205

It doesn't look like this change was on purpose, I've opened this pull-request to revert that part of it (the rest of the conditional appears fine).

**Comment by chew-z** [comment] 2017-06-25 03:35
Can't that be fixed with some quick patch? I had to switch off notifications for most of my AppleScript services because they hang otherwise forever waiting to hear back from terminal-notifier. Quite annoying.

**Comment by julienXX** [comment] 2017-06-25 15:45
@chew-z no, quick patch is always the wrong way to go. I'm working on it, in the meantime you can revert to 1.7.2.

**Comment by volans-** [comment] 2017-10-25 08:23
Is there any news/progress towards the solution of this?

**Comment by gms8994** [comment] 2017-10-26 14:37
This happens to me as well without using `-activate`, but instead using `-timeout`:

Mac Version: macSierra 10.12.5
terminal-notifier version: 1.8.0
Installation method: rubygems

`echo "HI" | terminal-notifier -title "TEST" -timeout 10`

I get a response of `2017-10-26 10:36:12.273 terminal-notifier[33324:20852242] @TIMEOUT`.

**Comment by julienXX** [comment] 2017-11-01 16:43
Version 2.0.0 as been released with alerter features removed https://github.com/julienXX/terminal-notifier/releases/tag/2.0.0 so this issue is not relevant anymore as there is no more waiting for user action.
Closing for now, feel free to re-open.

**Closed by julienXX** 2017-11-01 16:43 UTC
