### ISSUE TITLE
Hang When Running from Tmux on OS X 10.10 Yosemite

### ISSUE THREAD

**Issue by smackesey** [julienXX/terminal-notifier#115] opened 2014-10-27 16:33 UTC
When I run `terminal-notifier` from `tmux` on OS X 10.10 Yosemite, it hangs:

```
terminal-notifier -message "his name was robert paulson"
# ... hanging
```

It works fine when running it from outside tmux. This may have something to do with `reattach-to-user-namespace`. My tmux is configured with this line:

```
set-option -g default-command "reattach-to-user-namespace -l zsh"
```

Which was taken from the instructions from [this page](http://robots.thoughtbot.com/how-to-copy-and-paste-with-tmux-on-mac-os-x).

**Comment by buccolo** [comment] 2015-01-28 13:25
Hi @adamyonk,

Do you have any other configuration set? 

I have the same exact setup as you, but my terminal-notifier still hangs inside tmux.

```bash
~/ $ tmux -V
tmux 1.9a
~/ $ reattach-to-user-namespace --version
reattach-to-user-namespace version 2.3
    Supported OSes: OS X 10.5-10.10
~/ $ gem list terminal-notifier

*** LOCAL GEMS ***

terminal-notifier (1.6.2)
```

Also on Yosemite 10.10.1.

**Comment by adamyonk** [comment] 2015-01-28 17:15
Make sure you've killed/restarted tmux so you don't have an old session around. Beyond that, it looks like our setups are the same. I have this as my `default-command`:
```
set-option -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL"
```

**Comment by buccolo** [comment] 2015-01-28 17:33
Of course @adamyonk! 

I had disabled `reattach-to-user-namespace`. After enabling it back on I can see the notifications just fine.

Thanks :beers:

**Comment by adamyonk** [comment] 2015-01-28 18:21
@buccolo, oh good! So glad it worked!

**Comment by unphased** [comment] 2015-02-21 15:45
Can someone explain why `reattach-to-user-namespace` is required for terminal-notifier when inside tmux?

**Comment by ptbrowne** [comment] 2015-02-28 17:27
I use `fish` shell and `tmux`. I put `set-option -g default-command "reattach-to-user-namespace -l fish` in my `.tmux.conf` and it works now :+1: Thanks @adamyonk

**Comment by oschrenk** [comment] 2015-03-16 10:40
Thanks @adamyonk

**Comment by rbf** [comment] 2015-05-21 10:19
I had the same issue as described here, i.e. `terminal-notifier` worked only outside `tmux` since Mac OS X Yosemite. After reading this thread, I can confirm following steps solved the issue for me:

1. upgrade `tmux` form `1.9a` to `2.0` with `brew update && brew upgrade tmux`

1. install `reattach-to-user-namespace` with `brew update && brew install reattach-to-user-namespace`

1. add following lines to at the beginning of my `~/.tmux.conf` file (inspired from the [commit](https://github.com/sidwood/dotfiles/commit/dbde33e7374879c6c9a640e68e4d83e79b5fcbf4) referenced [above](https://github.com/alloy/terminal-notifier/issues/115#issuecomment-81571470)):

  ``` bash
  # Reattach each new window to the user bootstrap namespace
  # https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
  set -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL -l"
  ```

Step `1.` alone didn't fix the issue, but adding `reattach-to-user-namespace` did the trick. As a bonus I can finally use `pbcopy` and `pbpaste` inside `tmux`. :tada: 

My current working environment after the upgrades is the following:

``` shell
sw_vers -productVersion  # Mac OS Version
# 10.10.3
terminal-notifier -v | head -1
# terminal-notifier (1.6.3) is a command-line tool to send OS X User Notifications.
tmux -V
# tmux 2.0
reattach-to-user-namespace -v
# reattach-to-user-namespace version 2.3
#     Supported OSes: OS X 10.5-10.10
```

**Comment by waynew** [comment] 2015-05-23 15:43
That's odd - I have zero problems with pbcopy from within tmux, but the terminal notifier doesn't work

**Comment by unphased** [comment] 2015-05-23 17:31
@waynew Yeah, in a recent OS X release, pbcopy/pbpaste etc started to work fine without `reattach-to-user-namespace`. 

These days I don't run gulp on my mac anymore (CPU consumption), but when I do I just run it outside tmux. easy.

**Comment by konstan** [comment] 2015-05-27 12:52
FYI. Followed the steps listed by @rbf in https://github.com/alloy/terminal-notifier/issues/115#issuecomment-104214742 and now my side `terminal-notifier` no longer hangs when launched from `tmux`.

**Comment by e9t** [comment] 2015-06-27 09:50
For me, @rbf's comments helped.

I prepended reattach-to-user-namespace to terminal-notifier and fixed the issue.
So in my .bashrc:

    alias terminal-notifier='reattach-to-user-namespace terminal-notifier'

I've had [similar issues before with Sublime Text](http://superuser.com/a/843631/137947). Hope that helps in fixing the issue.

**Comment by jhirbour** [comment] 2017-01-25 20:46
` brew update && brew install reattach-to-user-namespace` from @rbf 

and 
`alias terminal-notifier='reattach-to-user-namespace terminal-notifier'`

worked for me. 

I opted for a terminal alias as I use a shared tmux.conf file (from a common dotfile repo).

**Comment by julienXX** [comment] 2017-05-13 22:56
Closing the issue, feel free to re-open if there is something I can help with.

**Closed by julienXX** 2017-05-13 22:56 UTC
Labels: 10.10, tmux
