### ISSUE TITLE
Including -sender option notification doesn't pop up

### ISSUE THREAD

**Issue by tshu-w** [julienXX/terminal-notifier#229] opened 2017-06-15 08:46 UTC
# Please check everything that applies to your issue:
- [ ] I looked in closed issues and it has not already been answered
- [x] My issue appeared with a terminal-notifier update
- [ ] I'm using a tool that uses terminal-notifier (guard-notifier, node-notifier...)

# To help us debug your issue please include:
- macOS version : 10.12.5 (16F73)
- terminal-notifier version: 1.8.0
- Install by homebrew
- reproduction instructions:

```
[terminal] ~$ terminal-notifier -title foo -message bar
[terminal] ~$ # Notification pops up
[terminal] ~$ terminal-notifier -title foo -message bar -sender 'com.apple.Terminal'
[terminal] ~$ # Notification doesn't pops up, but can be found in Notification Center.
```
Some issue in iterm2
```
[iterm2] ~$ terminal-notifier -title foo -message bar -sender 'com.googlecode.iterm2'
[iterm2] ~$ # Notification doesn't pops up, but can be found in Notification Center.
```

**Comment by julienXX** [comment] 2017-06-15 13:21
Hi @Voleking I think your issue is a duplicate of #216 do you confirm?

**Comment by Voleking** [comment] 2017-06-15 15:03
@julienXX yeah, sorry I didn't see it.

**Comment by tshu-w** [comment] 2020-06-01 12:05
This issue is still there but #216 was closed, so I reopen it again. see https://github.com/julienXX/terminal-notifier/issues/216#issuecomment-616864111

**Closed** 2020-06-01 23:43 UTC
